config/routes.rb
ThinReportsExample::Application.routes.draw do
  resources :estimates do
    member do
      get :report
    end
  end

  root to: 'estimates#index'

end

app/models/estimate.rb
class Estimate < ActiveRecord::Base
  attr_accessible :customer, :no, :place, :total_price
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/estimates_controller.rb
class EstimatesController < ApplicationController
  # GET /estimates
  # GET /estimates.json
  def index
    @estimates = Estimate.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @estimates }
    end
  end

  # GET /estimates/1
  # GET /estimates/1.json
  def show
    @estimate = Estimate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @estimate }
    end
  end

  def report
    @estimate = Estimate.find(params[:id])

    respond_to do |format|
      format.pdf
    end
  end

  # GET /estimates/new
  # GET /estimates/new.json
  def new
    @estimate = Estimate.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @estimate }
    end
  end

  # GET /estimates/1/edit
  def edit
    @estimate = Estimate.find(params[:id])
  end

  # POST /estimates
  # POST /estimates.json
  def create
    @estimate = Estimate.new(params[:estimate])

    respond_to do |format|
      if @estimate.save
        format.html { redirect_to @estimate, notice: 'Estimate was successfully created.' }
        format.json { render json: @estimate, status: :created, location: @estimate }
      else
        format.html { render action: "new" }
        format.json { render json: @estimate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /estimates/1
  # PUT /estimates/1.json
  def update
    @estimate = Estimate.find(params[:id])

    respond_to do |format|
      if @estimate.update_attributes(params[:estimate])
        format.html { redirect_to @estimate, notice: 'Estimate was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @estimate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estimates/1
  # DELETE /estimates/1.json
  def destroy
    @estimate = Estimate.find(params[:id])
    @estimate.destroy

    respond_to do |format|
      format.html { redirect_to estimates_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/estimates_helper.rb
module EstimatesHelper
end

app/views/estimates/_form.html.erb
<%= form_for(@estimate) do |f| %>
  <% if @estimate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@estimate.errors.count, "error") %> prohibited this estimate from being saved:</h2>

      <ul>
      <% @estimate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :no %><br />
    <%= f.text_field :no %>
  </div>
  <div class="field">
    <%= f.label :customer %><br />
    <%= f.text_field :customer %>
  </div>
  <div class="field">
    <%= f.label :total_price %><br />
    <%= f.number_field :total_price %>
  </div>
  <div class="field">
    <%= f.label :place %><br />
    <%= f.text_field :place %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/estimates/edit.html.erb
<h1>Editing estimate</h1>

<%= render 'form' %>

<%= link_to 'Show', @estimate %> |
<%= link_to 'Back', estimates_path %>

app/views/estimates/index.html.erb
<h1>Listing estimates</h1>

<table>
  <tr>
    <th>No</th>
    <th>Customer</th>
    <th>Total price</th>
    <th>Place</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @estimates.each do |estimate| %>
  <tr>
    <td><%= estimate.no %></td>
    <td><%= estimate.customer %></td>
    <td><%= estimate.total_price %></td>
    <td><%= estimate.place %></td>
    <td><%= link_to 'Show', estimate %></td>
    <td><%= link_to 'Edit', edit_estimate_path(estimate) %></td>
    <td><%= link_to 'Destroy', estimate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Estimate', new_estimate_path %>

app/views/estimates/new.html.erb
<h1>New estimate</h1>

<%= render 'form' %>

<%= link_to 'Back', estimates_path %>

app/views/estimates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>No:</b>
  <%= @estimate.no %>
</p>

<p>
  <b>Customer:</b>
  <%= @estimate.customer %>
</p>

<p>
  <b>Total price:</b>
  <%= @estimate.total_price %>
</p>

<p>
  <b>Place:</b>
  <%= @estimate.place %>
</p>


<%= link_to 'show pdf', report_estimate_path(@estimate, format: 'pdf') %> |
<%= link_to 'Edit', edit_estimate_path(@estimate) %> |
<%= link_to 'Back', estimates_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ThinReportsExample</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>